// Code generated by goctl. DO NOT EDIT.
package types

type RigsterReq struct {
	FlowUUID string   `json:"flow_uuid"`
	Backend  []string `json:"backend"`
	Model    []string `json:"model"`
	Zoo      string   `json:"zoo"`
}

type UnRigsterReq struct {
	FlowUUID string `json:"flow_uuid"`
}

type QueryReq struct {
	FlowUUID    string `json:"flow_uuid"`
	ImageBase64 string `json:"image_base64"`
}

type FaceResult struct {
	BBox     []float32   `json:"bbox"`
	Conf     float32     `json:"conf"`
	LandMark [][]float32 `json:"landmark"`
	Parsing  string      `json:"parsing"`
}

type ObjectResult struct {
	BBox  []float32 `json:"bbox"`
	Conf  float32   `json:"conf"`
	Label int       `json:"label"`
}

type OCRResult struct {
	Box        [][]float32 `json:"box"`
	Conf       float32     `json:"conf"`
	ConfRotate float32     `json:"conf_rotate"`
	Label      string      `json:"label"`
}

type ClsResult struct {
	Conf  float32 `json:"conf"`
	Label int     `json:"label"`
}

type QueryReply struct {
	Code      int            `json:"code"`
	Msg       string         `json:"msg"`
	Face      []FaceResult   `json:"face"`
	Object    []ObjectResult `json:"object"`
	Ocr       []OCRResult    `json:"ocr"`
	Cls       []ClsResult    `json:"cls"`
	Anime     string         `json:"anime"`
	Tddfa     string         `json:"tddfa"`
	KeyPoints [][]float32    `json:"key_points"`
}

type StatusReply struct {
	Msg  string `json:"msg"`
	Code int    `json:"code"`
}
