// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"aidb_go/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/aidb/register",
				Handler: registerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/aidb/unregister",
				Handler: unregisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/aidb/query",
				Handler: queryHandler(serverCtx),
			},
		},
		rest.WithPrefix("/talkuhulk"),
		rest.WithTimeout(3000*time.Millisecond),
	)
}
